### ISSUE TITLE
Can not seem to get working (probably a problem with my composer.json)

### ISSUE THREAD

**Issue by CrashyBang** [mnsami/composer-custom-directory-installer#11]
Here is my `composer.json`:
```
{
  "name": "Frontier-CMS",
  "description": "The best Frontend Engineer package around",
  "require": {
    "mnsami/composer-custom-directory-installer": "*",
    "frontier-app/cockpit": "*"
  },
  "extra":{
    "installer-paths":{
      "./admin/": ["frontier-app/cockpit"]
    }
  }
}
```
When I run `composer install` it just installs everything to the `vendor/` folder.

**Comment by mnsami** [comment]
hey @CrashyBang ... first sorry for the inconvenience.

I think because you defined your `composer.json` for your `frontier-app/cockpit` as a project and not as a library or package.

let me run some tests and get back to you soon.

**Comment by CrashyBang** [comment]
Thanks man :) thats really cool I am happy to change anything to make this work :+1:

**Comment by fnagel** [comment]
Same issues here :-/

**Comment by royduin** [comment]
An idea to support project types to? For example in combination with https://github.com/aheinze/cockpit/blob/master/composer.json.

**Comment by mnsami** [comment]
hello

First of all, sorry for the late reply, I had my wedding vacations for 1 month and came back busy with lots of project.

Relating this issue, I have already this issue open with the same request #7 .

**Comment by royduin** [comment]
Np, gefeliciteerd! (congrats in Dutch). Then we've to find another way.

**Comment by mnsami** [comment]
I would recommend changing the package `type` to something that is `composer` defined, as per the composer documentation https://getcomposer.org/doc/04-schema.md#type

> The type of the package. It defaults to library.
>
> Package types are used for custom installation logic. If you have a package that needs some special logic, you can define a custom type. This could be a symfony-bundle, a wordpress-plugin or a typo3-module. These types will all be specific to certain projects, and they will need to provide an installer capable of installing packages of that type.

which is something that makes sense to me.

what is your opinion?

@CrashyBang ??

**Comment by royduin** [comment]
I totally agree with you, I think Cockpit CMS should change it's type as suggested here: https://github.com/aheinze/cockpit/issues/261, but the author isn't responding so we're looking for other options. The suggestions made here are possibilities but those aren't that clean.

**Comment by mnsami** [comment]
And to be honest, I don't want to handle special handling for a very custom specific project.

The main goal here, is not to create another `composer installer` to support different projects, the main goal is to extend the functionality of composer.

So, do you mind if I close the ticket?

**Comment by royduin** [comment]
Sure no problem, but it's opened by @CrashyBang.

**Comment by mnsami** [comment]
True, I'll wait for @CrashyBang to reply first, but he was satisfied by the solution I told him as his problem was something different.

Anyways, I'll wait for him.

**Comment by mnsami** [comment]
Reporter is not responding, I'm closing the ticket until further notice.

**Comment by CrashyBang** [comment]
Hey @mnsami sorry have been al over the show lately, yes your initial suggestion worked well for me, sorry for not getting back sooner!

Cheers.
