### ISSUE TITLE
Problem with install to other folder

### ISSUE THREAD

**Issue by jbartoszek** [mnsami/composer-custom-directory-installer#12]
i have my package 

`{
    "name": "ab/abc",
    "description": "Desc of abc,
    "type": "package",
    "authors": [
        {
            "name": "Jacek",
            "email": "mail@mail.net"
        }
    ]
}`

and my composer.json file:

`{
  "repositories": [
    {
      "type": "vcs",
      "url": "git@bitbucket.org:ab/abc.git"
    }
  ],
  "prefer-stable": false,
  "require": {
    "mnsami/composer-custom-directory-installer": "*",
    "ab/abc": "v1.0.8"
  },
  "extra": {
    "installer-paths": {
      "./smothing/": ["ab/abc"]
    }
  }
}`
. When i make a `composer install` i have a this package in vendor/ab/abc. Why? I would have a this package in root folder next to a composer.json

Best Regards.
Jacek

**Comment by mnsami** [comment]
Hi @jbartoszek 

I'm sorry for the late reply, but unfortunately repositories are not handled by the composer installers, they are handled in a different complete manner using Repository Download manager, and unfortunately composer doesn't provide a way to override the behavior of those.

if you have an idea, I'm open to talk about it.

**Comment by mnsami** [comment]
Reporter is not responding, I'm closing the ticket.
