### ISSUE TITLE
Incompatibility with wikimedia/composer-merge-plugin

### ISSUE THREAD

**Issue by lpalgarvio** [mnsami/composer-custom-directory-installer#16]
Hello

The merge process of the composer-merge-plugin is probably happening after this plugin, meaning it doesn't get the merged json from merge-plugin.

https://github.com/wikimedia/composer-merge-plugin

Similar behavior with drupal-libraries-installer-plugin:
https://github.com/generalredneck/drupal-libraries-installer-plugin
https://github.com/generalredneck/drupal-libraries-installer-plugin/issues/3

Any clues?

**Comment by mnsami** [comment]
sorry, for not replying earlier.

I see you are also using my package heavily how can i help regarding this issue?

But I don't have any clue about the merging part.

**Comment by lpalgarvio** [comment]
Hello mnsami,

This issue might have been fixed in wikimedia/composer-merge-plugin#99 .
I will give another try as soon as possible. Will post back afterwards.

Thanks!

**Comment by mnsami** [comment]
appreciate it thanks!
