### ISSUE TITLE
[Enhancement] Implement a new variable {$version}

### ISSUE THREAD

**Issue by ZaDarkSide** [mnsami/composer-custom-directory-installer#18]
As with {$vendor} and {$name}, I would like to see a {$version} variable that will have the version of the package installed so that the following configuration:

``` json
    "extra": {
        "installer-paths": {
            "./libraries/{$name}-{$version}": ["vendor/pkgname"]
        }
    }
```

Will result in installing the package to the following directory:

```
 /libraries/pkgname-1.0.0
```

**Comment by mnsami** [comment]
hello @ZaDarkSide what is the use case behind this? is it possible to use same package twice with different versions in the same app?

**Comment by ZaDarkSide** [comment]
No, composer doesn't supports this, also PHP can't load the same class twice, but the use case is for the creation of the directory of the library to contain if you wish also the version number.

**Comment by mnsami** [comment]
@ZaDarkSide  appending the version number to the package directory name, looks to me a diversion from the main composer functionality, it doesn't mean anything as you can figure it out easily from your `composer.json` or `composer.lock` which is the most rightful place for it, I don't want to divert from the main composer functionality tbh.

**Comment by ZaDarkSide** [comment]
@mnsami Well what connection there is between how composer handles things and how I want to structure my project libraries? The structure of my project should be chosen by me, not dictated by composer. Why use this (composer-custom-directory-installer) if it does not allows you to make custom directories? What's the point?
