### ISSUE TITLE
Last release

### ISSUE THREAD

**Issue by drAlberT** [mnsami/composer-custom-directory-installer#19]
Should it be **1.1.0** ?

**Comment by mnsami** [comment]
there is a tag of 1.1.0 :)

**Comment by drAlberT** [comment]
I know, of course ... but the "Last Release" button still points to the previous one .. 

I think you have to double check something ;)

**Comment by mnsami** [comment]
thanks @drAlberT for spotting this, I had to push the release manually this time, thanks again!
