### ISSUE TITLE
Libraries.io version is out of sync

### ISSUE THREAD

**Issue by drAlberT** [mnsami/composer-custom-directory-installer#20]
Last version on [Libraries.io](https://libraries.io/packagist/mnsami%2Fcomposer-custom-directory-installer) is **1.1.0** .. it could be something related to #19 .. I don't know

This makes dependent project to see their dependencies **out-of-date** ;(

**Comment by mnsami** [comment]
I don't know how to fix this? any idea?

**Comment by drAlberT** [comment]
AFAICS now the release on libraries.io is the same as the one on GH  .. Am I missing your point?

**Comment by mnsami** [comment]
Well I am knowledgable with libraries.io, so I didn't know what do to make it fixed but looks like it is fixed now.
