### ISSUE TITLE
Custom packages install order

### ISSUE THREAD

**Issue by shemayas** [mnsami/composer-custom-directory-installer#21]
Is there a way to set a order to the installation of the packages?

Let's say I have two custom packages **test/a** and **test/b**,
I want to install the **test/a** in `src/` and then **test/b** in `src/app/` ,

The problem is that if the **test/b** will run first and will create `src/app/` then **test/a** will erase `src/app`, but if I have a way to ensure that **test/a** will run first, everything will be perfect.

Any ideas?

**Comment by mnsami** [comment]
easiest way is to adjust dependancies in each package `composer.json` so that you make `test/b` depends on `test/a`, then composer will install each based on dependancies because install order translates into dependancies in my opinion.
