### ISSUE TITLE
Difference to composer/installers? 

### ISSUE THREAD

**Issue by jcnventura** [mnsami/composer-custom-directory-installer#25]
I'm struggling to understand what is the difference between this and composer/installers. Both provide the same extra/installer-paths logic. Was this a precursor to what is now in composer core?

**Comment by mnsami** [comment]
Hi,

The `composer/installers` has logic that works only if you specify a specific type when developing / constructing your package. See here https://github.com/composer/installers#example-composerjson-file

Mine, just works only if you specify the parameters mentioned in the documentation on any composer package.

That is the main difference.

**Comment by mnsami** [comment]
@jcnventura do you still want this open?
