### ISSUE TITLE
Adding multiple repos to directory is failing.

### ISSUE THREAD

**Issue by bwaye3** [mnsami/composer-custom-directory-installer#31]
Trying to add several repos to a specific directory. Seems to skipping the 1st repo.
.json

{
    "name": "drupal/recommended-project",
    "description": "Project template for Drupal 9 projects with a relocated document root",
    "type": "project",
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.gatech.edu/ICWebTeam/block_alerts.git"
        },
        {
            "type": "vcs",
            "url": "https://github.gatech.edu/ICWebTeam/block_badges.git"
        },
        {
            "type": "vcs",
            "url": "https://github.gatech.edu/ICWebTeam/block_counter.git"
        }
    ],
    "require": {
        "gt/alerts": "dev-master",
        "gt/badges": "dev-master",
        "gt/counter": "dev-master",
        "mnsami/composer-custom-directory-installer": "^2.0",
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "sort-packages": true
    },

    "extra": {
        "drupal-scaffold": {
            "locations": {
                "web-root": "web/"
            }
        },
        "installer-paths": {
                 "web/themes/contrib/darwin/templates/block/custom/{$name}": [
                "gt/alerts",
                "gt/badges",
                "gt/counter"
            ]
        },
        "drupal-core-project-message": {
            "include-keys": [
                "homepage",
                "support"
            ],
            "post-create-project-cmd-message": [
                "<bg=blue;fg=white>                                                         </>",
                "<bg=blue;fg=white>  Congratulations, you’ve installed the Drupal codebase  </>",
                "<bg=blue;fg=white>  from the drupal/recommended-project template!          </>",
                "<bg=blue;fg=white>                                                         </>",
                "",
                "<bg=yellow;fg=black>Next steps</>:",
                "  * Install the site: https://www.drupal.org/docs/8/install",
                "  * Read the user guide: https://www.drupal.org/docs/user_guide/en/index.html",
                "  * Get support: https://www.drupal.org/support",
                "  * Get involved with the Drupal community:",
                "      https://www.drupal.org/getting-involved",
                "  * Remove the plugin that prints this message:",
                "      composer remove drupal/core-project-message"
            ]
        }
    }
}

**Comment by mnsami** [comment]
Hi @bwaye3 

Currently, it doesn't accept multiple repos in the same way you are doing it. But, In order for you to add multiple you have to add multiple entries for each repo.

let me know if you need help further.

thanks.

**Comment by mnsami** [comment]
closing because no response from reporter
