### ISSUE TITLE
Problems with composer-custom-directory-installer

### ISSUE THREAD

**Issue by pablor** [mnsami/composer-custom-directory-installer#7]
Hi @mnsami,
Fisrt of all thanks for your work!
I'm trying to use your installer and I have some problems. With that `composer.json` everything works OK:
```
{
    "name": "test/testign",
    "description": "Tetsting",
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:mnsami/composer-custom-directory-installer.git"
        }
    ],
    "require": {
        "php": ">=5.3",
        "mnsami/composer-custom-directory-installer": "1.0.*",
        "monolog/monolog": "*"
    },
    "extra": {
        "installer-paths": {
            "./monolog/": ["monolog/monolog"]
        }
    },
    "minimum-stability": "dev"
}
```

The monolog library was placed in the `./monolog` directory as expected. But, if I use my own repo, it doesn't place the [pablor/test-library](https://github.com/pablor/test-library) inside the `./monolog` directory.
```
{
    "name": "test/testign",
    "description": "Testing",
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:mnsami/composer-custom-directory-installer.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/pablor/test-library"
        }
    ],
    "require": {
        "php": ">=5.3",
        "mnsami/composer-custom-directory-installer": "1.0.*",
        "pablor/test-library": "*",
        "monolog/monolog": "*"
    },
    "extra": {
        "installer-paths": {
            "./monolog/": ["pablor/test-library"]
        }
    },
    "minimum-stability": "dev"
}
```

Any idea about waht I'm doing wrong?
Thanks!

**Comment by mnsami** [comment]
Hi @pablor 

After doing some investigations, you `package` is of type `project` and `composer ProjectInstaller` handles anything with type `project` to be installed in the root of clean directory.

Check https://github.com/composer/composer/blob/master/src/Composer/Installer/ProjectInstaller.php#L61

The best thing you can do, is change the type of your composer package to something that the composer installers can handle.

The idea with my plugin here, is to provide customization for the composer installers without altering how composer function or doing some dirty hacks.
